'use strict';

/**
 * TLD -> WHOIS 服务器映射表。
 *
 * 这不是全部(全球有 1500+ 个 TLD),但覆盖了绝大多数常用后缀。
 * 未收录的 TLD 会走 IANA 自动转介(lib/whois.js 会先问 whois.iana.org),
 * 所以这里只是一个"加速 + 提高命中率"的缓存。
 */

const TLDS = {
  // ---- 通用顶级域 gTLD ----
  com: 'whois.verisign-grs.com',
  net: 'whois.verisign-grs.com',
  org: 'whois.pir.org',
  info: 'whois.afilias.net',
  biz: 'whois.nic.biz',
  name: 'whois.nic.name',
  pro: 'whois.afilias.net',
  mobi: 'whois.nic.mobi',
  asia: 'whois.nic.asia',
  tel: 'whois.nic.tel',
  xxx: 'whois.nic.xxx',
  travel: 'whois.nic.travel',
  jobs: 'whois.nic.jobs',
  cat: 'whois.nic.cat',
  coop: 'whois.nic.coop',
  aero: 'whois.aero',
  museum: 'whois.museum',

  // ---- 新通用顶级域 new gTLD ----
  app: 'whois.nic.google',
  dev: 'whois.nic.google',
  page: 'whois.nic.google',
  new: 'whois.nic.google',
  day: 'whois.nic.google',
  how: 'whois.nic.google',
  so: 'whois.nic.so',
  xyz: 'whois.nic.xyz',
  top: 'whois.nic.top',
  club: 'whois.nic.club',
  online: 'whois.nic.online',
  site: 'whois.nic.site',
  shop: 'whois.nic.shop',
  store: 'whois.nic.store',
  tech: 'whois.nic.tech',
  space: 'whois.nic.space',
  website: 'whois.nic.website',
  press: 'whois.nic.press',
  host: 'whois.nic.host',
  fun: 'whois.nic.fun',
  icu: 'whois.nic.icu',
  vip: 'whois.nic.vip',
  wang: 'whois.nic.wang',
  ren: 'whois.nic.ren',
  art: 'whois.nic.art',
  blog: 'whois.nic.blog',
  cloud: 'whois.nic.cloud',
  design: 'whois.nic.design',
  email: 'whois.nic.email',
  live: 'whois.nic.live',
  ltd: 'whois.nic.ltd',
  media: 'whois.nic.media',
  network: 'whois.nic.network',
  news: 'whois.nic.news',
  one: 'whois.nic.one',
  pub: 'whois.nic.pub',
  rocks: 'whois.nic.rocks',
  run: 'whois.nic.run',
  software: 'whois.nic.software',
  studio: 'whois.nic.studio',
  systems: 'whois.nic.systems',
  today: 'whois.nic.today',
  tools: 'whois.nic.tools',
  wiki: 'whois.nic.wiki',
  work: 'whois.nic.work',
  world: 'whois.nic.world',
  zone: 'whois.nic.zone',
  agency: 'whois.nic.agency',
  company: 'whois.nic.company',
  digital: 'whois.nic.digital',
  group: 'whois.nic.group',
  life: 'whois.nic.life',
  link: 'whois.nic.link',
  money: 'whois.nic.money',
  plus: 'whois.nic.plus',
  team: 'whois.nic.team',
  center: 'whois.nic.center',
  city: 'whois.nic.city',
  education: 'whois.nic.education',
  finance: 'whois.nic.finance',
  foundation: 'whois.nic.foundation',
  institute: 'whois.nic.institute',
  international: 'whois.nic.international',
  marketing: 'whois.nic.marketing',
  solutions: 'whois.nic.solutions',
  support: 'whois.nic.support',
  training: 'whois.nic.training',
  ventures: 'whois.nic.ventures',
  codes: 'whois.nic.codes',
  computer: 'whois.nic.computer',
  directory: 'whois.nic.directory',
  graphics: 'whois.nic.graphics',
  management: 'whois.nic.management',
  photos: 'whois.nic.photos',
  pictures: 'whois.nic.pictures',
  services: 'whois.nic.services',
  social: 'whois.nic.social',
  tips: 'whois.nic.tips',

  // ---- 国家/地区顶级域 ccTLD ----
  cn: 'whois.cnnic.cn',
  '中国': 'whois.cnnic.cn',
  '公司': 'whois.cnnic.cn',
  '网络': 'whois.cnnic.cn',
  tw: 'whois.twnic.net.tw',
  hk: 'whois.hkirc.hk',
  mo: 'whois.monic.mo',
  jp: 'whois.jprs.jp',
  kr: 'whois.kr',
  sg: 'whois.sgnic.sg',
  my: 'whois.mynic.my',
  th: 'whois.thnic.co.th',
  vn: 'whois.vnnic.vn',
  ph: 'whois.dot.ph',
  id: 'whois.id',
  in: 'whois.registry.in',
  pk: 'whois.pknic.net.pk',
  bd: 'whois.btcl.net.bd',
  lk: 'whois.nic.lk',
  np: 'whois.nic.np',
  io: 'whois.nic.io',
  ai: 'whois.nic.ai',
  co: 'whois.nic.co',
  me: 'whois.nic.me',
  tv: 'whois.nic.tv',
  cc: 'ccwhois.verisign-grs.com',
  ws: 'whois.website.ws',
  ly: 'whois.nic.ly',
  us: 'whois.nic.us',
  ca: 'whois.cira.ca',
  mx: 'whois.mx',
  br: 'whois.registro.br',
  ar: 'whois.nic.ar',
  cl: 'whois.nic.cl',
  pe: 'whois.rcp.net.pe',
  ve: 'whois.nic.ve',
  uy: 'whois.nic.org.uy',
  ru: 'whois.tcinet.ru',
  su: 'whois.tcinet.ru',
  ua: 'whois.ua',
  by: 'whois.by',
  kz: 'whois.nic.kz',
  uz: 'whois.cctld.uz',
  am: 'whois.amnic.net',
  ge: 'whois.nic.ge',
  az: 'whois.az',
  tr: 'whois.trabis.gov.tr',
  il: 'whois.isoc.org.il',
  sa: 'whois.nic.net.sa',
  ae: 'whois.aeda.net.ae',
  qa: 'whois.registry.qa',
  kw: 'whois.kw',
  om: 'whois.registry.om',
  bh: 'whois.nic.bh',
  jo: 'whois.nic.jo',
  lb: 'whois.nic.lb',
  eg: 'whois.ripe.net',
  za: 'whois.registry.net.za',
  ng: 'whois.nic.net.ng',
  ke: 'whois.kenic.or.ke',
  gh: 'whois.nic.gh',
  tz: 'whois.tznic.or.tz',
  ug: 'whois.co.ug',
  ma: 'whois.registre.ma',
  tn: 'whois.ati.tn',
  dz: 'whois.nic.dz',
  eu: 'whois.eu',
  uk: 'whois.nic.uk',
  de: 'whois.denic.de',
  fr: 'whois.nic.fr',
  nl: 'whois.domain-registry.nl',
  be: 'whois.dns.be',
  it: 'whois.nic.it',
  es: 'whois.nic.es',
  pt: 'whois.dns.pt',
  pl: 'whois.dns.pl',
  cz: 'whois.nic.cz',
  sk: 'whois.sk-nic.sk',
  hu: 'whois.nic.hu',
  ro: 'whois.rotld.ro',
  bg: 'whois.register.bg',
  gr: 'whois.nic.gr',
  hr: 'whois.dns.hr',
  si: 'whois.si',
  rs: 'whois.rnids.rs',
  ba: 'whois.biz.ba',
  mk: 'whois.marnet.mk',
  al: 'whois.aknet.org.al',
  md: 'whois.nic.md',
  lt: 'whois.domreg.lt',
  lv: 'whois.nic.lv',
  ee: 'whois.tld.ee',
  fi: 'whois.fi',
  se: 'whois.iis.se',
  no: 'whois.norid.no',
  dk: 'whois.dk-hostmaster.dk',
  is: 'whois.isnic.is',
  ie: 'whois.weare.ie',
  ch: 'whois.nic.ch',
  li: 'whois.nic.li',
  at: 'whois.nic.at',
  lu: 'whois.dns.lu',
  mt: 'whois.nic.org.mt',
  cy: 'whois.nic.cy',
  au: 'whois.auda.org.au',
  nz: 'whois.srs.net.nz',

  // ---- 基础设施 ----
  arpa: 'whois.iana.org',
  int: 'whois.iana.org',
  edu: 'whois.educause.edu',
  gov: 'whois.dotgov.gov',
  mil: 'whois.nic.mil',
};

/** 需要在查询时加特定前缀/指令的服务器 */
const QUERY_PREFIX = {
  'whois.denic.de': '-T dn,ace ',
  'whois.nic.fr': '',
  'whois.dns.be': '',
  'whois.nic.it': '',
  'whois.nic.cz': '',
};

/** 二次转介:某些注册局的 WHOIS 服务器不直接给结果,需要再转一次 */
const REFERRAL_FOLLOW = new Set([
  'whois.verisign-grs.com',
  'whois.pir.org',
  'whois.nic.io',
  'whois.nic.co',
  'whois.nic.me',
  'whois.nic.tv',
  'ccwhois.verisign-grs.com',
  'whois.nic.us',
  'whois.afilias.net',
  'whois.nic.biz',
]);

/** 该服务器的响应中只有"注册局"信息,必须跟随 Registrar WHOIS Server 再查一次 */
const REGISTRY_ONLY = new Set([
  'whois.verisign-grs.com',
  'ccwhois.verisign-grs.com',
  'whois.pir.org',
  'whois.nic.io',
  'whois.nic.co',
  'whois.nic.me',
  'whois.nic.tv',
]);

module.exports = { TLDS, QUERY_PREFIX, REFERRAL_FOLLOW, REGISTRY_ONLY };
